### ISSUE TITLE
A typo in write-points

### ISSUE THREAD

**Issue by i-perminov** [mmaul/cl-influxdb#1]
In write-points request parameter name should be "time_precision" instead of "time-precision".

**Comment by mmaul** [comment]
Thanks for the input. Issue is fixed. Be advised in current-ish release of influxdb continous queries is broken. Apparently the JSON API has changed WRT to continuous queries, I have a post to the mailing list, regarding the spec. Otherwise I'll dig into the influxdb source and find out what changed.
